export const PREDEFINED_ITEMS = [
  "15x11 1 Ply", "9.5x11 2 Ply", "15x11 2 Ply", "9.5x11 1 Ply", "A3", "A4 80",
  "A4 Blue", "A4 Green", "A4 Orange", "A4 Pink", "A4 Yellow", "A4 Read", "A4 70 gsm",
  "Binding Tape - Blue", "Binding Tape - Green", "Binding Tape - Red", "Binding Tape - Yellow",
  "Binding Tape - Black", "B5 75 gsm", "Bainder Glue (L)", "Bainder Glue (M)",
  "Bainder Glue Needle", "Bainder Nul", "Bristal Boord", "Buldo Clip",
  "Carbon Pen Blue", "Carbon Pen Black", "Carbon Pen Red", "CR Book - 40",
  "CR Book - 80", "CR Book - 120", "CR Book - 160", "CR Book - 200", "Calculater",
  "Celotape - 01", "Celotape - 02", "Carbon Paper 1 Side", "Carbon Paper 2 Side",
  "CD Drive", "Cheep Board", "Dimy Paper Green", "Drowing Pin", "Duplo Ink",
  "Envelopes 6x3 1/2", "Envelopes 9x6", "Envelopes 9x4", "Envelopes 9 1/2x4 1/2",
  "Envelopes 10x7", "Envelopes 10x15", "Epson Ink Boteel - 664", "Epson Ink Boteel - 774",
  "Eraser", "Fax Role", "File Print", "File Nomal", "File Thik", "File Clip",
  "File Tag", "File Pin Box", "Floppy Disk", "Half Sheet", "Hilight", "Heel Tag (4)",
  "InK Bottel", "Ink Pad", "Kapuru Bola", "Key Bord", "Maker", "Magazine Holder",
  "Master Role", "Mouse", "Paper Stick Rainbow", "Paper Stick Yellow", "Paper Cutter",
  "Pencil", "Pencil Cutter", "Pen Drive 16 GB", "Pen Drive 32", "Pen Drive 64",
  "Polothin", "Puncher", "Red Tape", "Ring File", "Ribbon LQ 2090", "Ribbon LQ 310",
  "Ronio Ink Bottel", "Rubeer Band", "Ruller", "Scissor (L)", "Scissor (M)",
  "Scanner -Flat bed", "Serviate", "Sing Pen", "Stepler Pin", "Stepler Pin Small",
  "Stepler Pin Machone", "Stepler Remove", "Stencil Paper",
  "T 220 BTD 60 bk Ink (Brother Printer) IT Unit", "T220 BT 5000 Color Ink -IT Unit",
  "790 Canon Ink", "005 Imk Epson Printer Land", "Toner 26 A(Account)",
  "Toner 2518 -Pantum Printer (Pension)", "3305 DW Pantum Toner -Aswasuma",
  "2500 W pantum Toner - Admin", "6200 HL -Brother Toner - Aswasuma",
  "TK 4109 Toner -Account", "2323 Toner - Toshiba", "2309 Toner",
  "NPG 28 Toner Canon", "Ricoh MP 2014 HS Toner -Admon", "NPg 59 Canon Toner -Land",
  "Note Book", "Nomal Glue", "Leegal", "Warnish", "White Board Eraser", "Wifi Adapter"
];
